server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://47.108.59.160:3306/template?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1200000
      minimum-idle: 0
      maximum-pool-size: 500
  redis:
    host: 47.108.59.160
    port: 6379
    database: 0
    password:
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

captchaType: math
template:
  thread:
    corePoolSize: 10
    maxPoolSize: 200
    queueCapacity: 1000
    keepAliveSeconds: 300

